version: '3'

services:
  web:
    build: .
    ports:
      - "9499:80"
    depends_on:
      - db
  db:
    image: mariadb:latest
    volumes:
      - /srv/skyoj-dev/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sky
      MYSQL_USER: skyuser
      MYSQL_PASSWORD: skypassword
